### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Blendart - A Photo Editor App
email: prodevelopers.ai@gmail.com
description: Blendart is power packed with an amazing features that you can edit like a pro.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/Rajpolu/Blendart-A-Photo-Editor-App" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
twitter_username: rockyprreddy
github_username:  rajpolu
author: Rajasekhar Reddy Polu
logo: assets/images/large-logo.png
twitter:
  username: rockyprreddy
social:
  name: Rajasekhar Reddy Polu
  links:
    - https://twitter.com/rockyprreddy  
    - https://www.facebook.com/rajpolu71
    - https://www.linkedin.com/in/rajasekharreddypolu
    - https://plus.google.com/+rockyprreddy
    - https://github.com/rajpolu

languages: ["en"]
ampdir: amp

github: https://github.com/Rajpolu/Blendart-A-Photo-Editor-App

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
